# 极简Jekyll配置
title: "Chico Gong's Tech Blog"
description: "对话式AI专家 & 实时通信开发者"
url: "https://realtime-ai.chat"
baseurl: ""

# 作者信息
author:
  name: "Chico Gong"
  email: "chicogong@tencent.com"
  github: "chicogong"
  bio: "对话式AI专家 & 实时通信开发者"

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _config_simple.yml

# 包含文件
include:
  - _pages

# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Chico Gong"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
